"""Reward and task constants for the 2D checkpoint exploration assignment."""

ROOMS_SCALE = 1.5

COVERAGE_GOAL_SLOTS = 5
COVERAGE_CELL_SIZE = int(80 * ROOMS_SCALE)
COVERAGE_HOVER_SPEED_THRESHOLD = 0.25
COVERAGE_HOVER_PENALTY = 0.004
COVERAGE_BLOCKED_WALL_PENALTY = 0.02
COVERAGE_COLLISION_PENALTY_CAP = 0.5
COVERAGE_COLLISION_PENALTY_RATE = 0.4
COVERAGE_PROGRESS_PENALTY = 0.002
COVERAGE_PROGRESS_MARGIN = 0.5

CHECKPOINT_REWARD = 0.5
CHECKPOINT_VISIBILITY_WALL_MARGIN = int(14 * ROOMS_SCALE)
CHECKPOINT_CROSS_TOLERANCE = int(10 * ROOMS_SCALE)
CHECKPOINT_TARGET_SAMPLES = 7
CHECKPOINT_TARGET_TRIM = 0.12
CHECKPOINT_CROSS_TRIM = 0.04

SENSOR_ORIGIN_WALL_BLOCK_MARGIN = int(8 * ROOMS_SCALE)
ROBOT_WALL_CLEARANCE = int(14 * ROOMS_SCALE)


def max_checkpoint_reward(n_checkpoints):
    return n_checkpoints * CHECKPOINT_REWARD
